### ISSUE TITLE
YouTube - Towards Bayesian Regression & Inference

### ISSUE THREAD

**Issue by ksachdeva** [aayushmalik/awesome-bayesian-statistics#2]
Hi @aayushmalik 

Many thanks for this collection. This is a really good compilation.

Here is the link to the playlist of videos on my YouTube channel on this subject. It is still a work in progress and would be publishing many more in this series.

https://youtube.com/playlist?list=PLivJwLo9VCUISiuiRsbm5xalMbIwOHOOn

If you think it is suitable to be included in this repo please feel free to add it.

Regards
Kapil

**Comment by aayushmalik** [comment]
Thank you for your suggestion Kapil. I have added your playlist. If there is any other material, you would like me to add, please create a pull request.
